# Generated by Django 4.2.6 on 2024-01-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_profileimage_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, default='https://www.nicepng.com/png/full/959-9595523_blank-facebook-cover-ivory.png', null=True, upload_to='account/images/'),
        ),
    ]
